export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILED = 'FETCHING_DATA_FAILED';
export const RESET_STATE = 'RESET_STATE';
export const OPEN_LOADING = 'OPEN_LOADING';
export const CLOSE_LOADING = 'CLOSE_LOADING';