export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILED = 'FETCHING_DATA_FAILED';
export const RESET_STATE = 'RESET_STATE';